version: "3.7"

services:

  postgres:
    container_name: read-it-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - read-it-postgres-data:/data/postgres
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    networks:
      - infrastructure
    env_file:
      - env/ReadIt_Postgres.env

networks:
  infrastructure:
    name: infrastructure
    driver: bridge

volumes:
  read-it-postgres-data:
    name: read-it-postgres-data
  

